# Generated by Django 3.2 on 2022-11-18 13:50

from django.db import migrations


def add_contributors(apps, schema_migration):
    Blog = apps.get_model('blog', 'Blog')
    blogs = Blog.objects.all()
    for blog in blogs:
        blog.contributors.add(blog.author, through_defaults={'contribution': 'Auteur principal'})


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20221118_1344'),
    ]

    operations = [
        migrations.RunPython(add_contributors)
    ]
